workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "project"

stages:
  - test

temp:
  stage: test
  image: docker:24.0.5
  tags: 
    - docker-compose 
  script:
    - ls -a /var/run/
    - apk add docker-compose
    - docker-compose up -d
