workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "project"

stages:
  - test
  - deploy

test:
  stage: test
  image: docker:24.0.5
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
  tags: 
    - docker-compose 
  before_script:
    - whoami
    - apk add npm
    - ls -l /var/run/docker.sock
    - echo $DOCKER_HOST
    - docker --version
    - docker-compose --version
    - docker-compose build --no-cache
    - docker-compose up -d
  script:
    - cd tests
    - npm install
    - npm run test
  after_script:
    - pwd
    - cd ..
    - docker-compose down
