workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "project"

stages:
  - test

temp:
  stage: test
  image: docker:latest
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
  tags: 
    - docker-compose 
  before_script:
    - ls /var/run
    - echo $DOCKER_HOST
    - docker --version
    - docker-compose --version
  script:
    - docker-compose build --no-cache
    - docker-compose up -d
