workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "project"

stages:
  - test
  - deploy

test1:
  stage: test
  variables:
    DOCKER_HOST: "unix:///runner/services/docker/docker.sock"
  services:
    - docker:24.0.5-dind
  image: docker:24.0.5
  script:
    - docker --version

test2:
  stage: deploy
  variables:
    DOCKER_HOST: "unix:///var/run/docker.sock"
  image: docker/compose:1.29.2
  tags: 
    - docker-compose 
  script:
    - docker-compose build --no-cache
    - docker-compose up -d
  before_script:
    - echo $DOCKER_HOST
    - docker --version
    - docker-compose --version
