workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "project"

stages:
  - test

temp:
  stage: test
  image: tmaier/docker-compose:latest
  tags: 
    - docker-compose 
  before_script:
    - docker --version
    - docker-compose --version
  script:
    - docker-compose build --no-cache
    - docker-compose up -d
