workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "project"

stages:
  - test

temp:
  stage: test
  tags: 
    - docker-compose 
  script:
    - docker-compose build --no-cache
    - docker-compose up -d
  before_script:
    - echo $DOCKER_HOST
    - docker --version
    - docker-compose --version
