workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "project"

stages:
  - test
  - deploy

run tests:
  stage: test
  image: docker:20
  services:
    - docker:24.0.5-dind # docker-in-docker
  tags:
    - docker-compose
    - test
  before_script:
    - pwd
    - apk add nodejs npm docker-compose
    - node -v
    - npm -v
    - docker info
    - docker-compose up -d
  script:
    - cd tests
    - npm install
    - npm test
  after_script:
    - pwd
    - [[ $(pwd) == */tests ]] && cd ..
    - docker-compose down

deploy:
  image: docker/compose:1.29.2
  stage: deploy
  tags: 
    - docker-compose 
  script:
    - docker-compose build --no-cache
    - docker-compose up -d
  before_script:
    - docker --version
    - docker-compose --version
