services:
  service1-1:
    image: service1
    container_name: service_1_1
    networks:
      - loadbalancing
      - backend
    expose:
      - "${SERVICE1_PORT}"
    environment:
      - PORT=${SERVICE1_PORT}
      - BE_PORT=${SERVICE2_PORT} 
      - WAIT_TIME_MS=${SERVICE1_WAIT_TIME_MS}
    build:
      context: app1
      dockerfile: Dockerfile
    depends_on:
      - service2

  service1-2:
    image: service1
    container_name: service_1_2
    networks:
      - loadbalancing
      - backend
    expose:
      - "${SERVICE1_PORT}"
    environment:
      - PORT=${SERVICE1_PORT}
      - BE_PORT=${SERVICE2_PORT}
      - WAIT_TIME_MS=${SERVICE1_WAIT_TIME_MS}
    build:
      context: app1
      dockerfile: Dockerfile
    depends_on:
      - service2


  service1-3:
    image: service1
    container_name: service_1_3
    networks:
      - loadbalancing
      - backend
    expose:
      - "${SERVICE1_PORT}"
    environment:
      - PORT=${SERVICE1_PORT}
      - BE_PORT=${SERVICE2_PORT}
      - WAIT_TIME_MS=${SERVICE1_WAIT_TIME_MS}
    build:
      context: app1
      dockerfile: Dockerfile
    depends_on:
      - service2


  service2:
    image: service2
    container_name: service_2
    networks:
      - backend
    expose:
      - "${SERVICE2_PORT}"
    environment:
      - PORT=${SERVICE2_PORT}
    build:
      context: app2
      dockerfile: Dockerfile
    volumes:     
      - /var/run/docker.sock:/var/run/docker.sock

 
  nginx:
    image: nginx:1-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/index.html:/var/www/index.html
    command: /bin/sh -c "envsubst '$${SERVICE1_PORT} $${INCOMING_TRAFFIC_PORT}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    ports:
      - "${INCOMING_TRAFFIC_PORT}:${INCOMING_TRAFFIC_PORT}"
    environment:
      - SERVICE1_PORT=${SERVICE1_PORT}
      - INCOMING_TRAFFIC_PORT=${INCOMING_TRAFFIC_PORT}
    networks:
      - loadbalancing
      - backend
    depends_on:
      - service1-1
      - service1-2
      - service1-3
      - service2

networks:
  loadbalancing:
    driver: bridge
  backend:
