services:
  frontend:
    image: node-docker
    container_name: my_frontend
    depends_on:
      - backend
    networks:
      - front-tier
      - back-tier
      - app-network
    expose:
      - "3000"
    build:
      context: app1
      dockerfile: Dockerfile

  backend:
    image: go-docker
    container_name: my_backend
    networks:
      - back-tier
    expose:
      - "8080"
    build:
      context: app2
      dockerfile: Dockerfile

  nginx:
    image: nginx:1-alpine
    container_name: my_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8198:8198"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  front-tier: {}
  back-tier: {}
