services:
  service1:
    image: service1
    networks:
      - loadbalancing
      - backend
    expose:
      - "${SERVICE1_PORT}"
    environment:
      - PORT=${SERVICE1_PORT}
      - BE_PORT=${SERVICE2_PORT}
      - WAIT_TIME_MS=${SERVICE1_WAIT_TIME_MS}
    build:
      context: app1
      dockerfile: Dockerfile
    depends_on:
      - service2
    deploy:
      mode: replicated
      replicas: 3

  service2:
    image: service2
    networks:
      - backend
    expose:
      - "${SERVICE2_PORT}"
    environment:
      - PORT=${SERVICE2_PORT}
    build:
      context: app2
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx:1-alpine
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/index.html:/var/www/index.html
    command: /bin/sh -c "envsubst '$${SERVICE1_PORT} $${INCOMING_TRAFFIC_PORT}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    ports:
      - "${INCOMING_TRAFFIC_PORT}:${INCOMING_TRAFFIC_PORT}"
    environment:
      - SERVICE1_PORT=${SERVICE1_PORT}
      - INCOMING_TRAFFIC_PORT=${INCOMING_TRAFFIC_PORT}
    networks:
      - loadbalancing
      - backend
    depends_on:
      - service1

networks:
  loadbalancing:
    driver: bridge
  backend:
    driver: bridge
